repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix --config=code_quality/.ruff.toml --exclude core --exclude tests
        language: system
        types: [python]
        exclude: '^(core|manage\.py|tests)'

      - id: ruff-format
        name: ruff-format
        entry: ruff format --config=code_quality/.ruff.toml
        language: system
        types: [python]
        exclude: '^(core|manage\.py)'

      - id: mypy
        name: mypy
        entry: mypy --config-file=code_quality/mypy.ini apps/
        language: system
        types: [python]
        pass_filenames: false

      - id: pylint
        name: pylint
        entry: pylint --rcfile=code_quality/pylint.toml apps/
        language: system
        types: [python]
        pass_filenames: false
        verbose: true

      - id: pytest
        name: pytest
        entry: python -m pytest tests/ -q
        language: system
        types: [python]
        pass_filenames: false
